// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmifbrkSLAu-kxxUTb8k8Q-CNJE9ZUVa4',
    appId: '1:739480525495:web:954aa01de6caa70d614b32',
    messagingSenderId: '739480525495',
    projectId: 'authentication-58de3',
    authDomain: 'authentication-58de3.firebaseapp.com',
    storageBucket: 'authentication-58de3.appspot.com',
    measurementId: 'G-7W10SFJW6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFFZ543m0PCn_gzqR00aVmasONGZcheI',
    appId: '1:739480525495:android:f0eff5e02c557e45614b32',
    messagingSenderId: '739480525495',
    projectId: 'authentication-58de3',
    storageBucket: 'authentication-58de3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWSqHyBeADTubOvGTdBMWCMwGC8mLhN_c',
    appId: '1:739480525495:ios:b22062fdc4365e53614b32',
    messagingSenderId: '739480525495',
    projectId: 'authentication-58de3',
    storageBucket: 'authentication-58de3.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWSqHyBeADTubOvGTdBMWCMwGC8mLhN_c',
    appId: '1:739480525495:ios:e32a803cfa6e1edf614b32',
    messagingSenderId: '739480525495',
    projectId: 'authentication-58de3',
    storageBucket: 'authentication-58de3.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
